# Arrays

# Basics

In [1]:
import array as arr

In [2]:
a=arr.array('i',[3,6,5])               #creating an array a
a

array('i', [3, 6, 5])

In [3]:
b=arr.array('i',[4,2,1])              #creating an array b
b

array('i', [4, 2, 1])

# slicing

In [4]:
a[0:]                                #slicing

array('i', [3, 6, 5])

In [5]:
a[::1]                               #slicing in the forward direction

array('i', [3, 6, 5])

In [6]:
a[::-1]                              #slicing in the reverse direction


array('i', [5, 6, 3])

In [7]:
a[:0]                               #slicing at 0

array('i')

In [8]:
a[:1]                               #slicing at 1

array('i', [3])

In [9]:
a.append(1)                        #append of 1
a

array('i', [3, 6, 5, 1])

In [10]:
b.pop()                           #pop operation
b

array('i', [4, 2])

In [11]:
a.pop()                          #pop operation
a

array('i', [3, 6, 5])

In [12]:
a

array('i', [3, 6, 5])

In [13]:
a.remove(a[2])                 #remove operation
a

array('i', [3, 6])

In [14]:
a

array('i', [3, 6])

In [15]:
a.remove(a[1])              #remove operation
a

array('i', [3])

In [16]:
a.pop()                    #pop operation
a

array('i')

In [17]:
a

array('i')

In [18]:
b.pop()                   #pop of last element

2

In [19]:
b

array('i', [4])

In [20]:
c=arr.array('i',[5,6,7])  #creating an array c
c

array('i', [5, 6, 7])

In [21]:
c.pop(0)                 #pop of c
c

array('i', [6, 7])

In [22]:
a

array('i')

In [23]:
b

array('i', [4])

In [24]:
b.pop(0)             #pop operation
b

array('i')

In [25]:
for i in c:         #getting all elements in c
    print(i)

6
7


In [26]:
for i in c:              #getting all elements in c horizontally
    print(i,end=" ")

6 7 

In [27]:
a+b                            #addition operation

array('i')

In [28]:
c+a                            #addition operation

array('i', [6, 7])

In [29]:
c+b                           #addition operation

array('i', [6, 7])

# Numpy

# pip install numpy

In [30]:
import numpy as np            #importing numpy

In [31]:
g=np.array([(1,2,4),(3,5,6)])    #creating a matrix g using numpy
h=np.array([(7,8,9),(2,6,1)])    #creating b matrix h using numpy
g

array([[1, 2, 4],
       [3, 5, 6]])

In [32]:
h

array([[7, 8, 9],
       [2, 6, 1]])

In [33]:
g.ndim                          #finding dimensional matrix of g

2

In [34]:
g.itemsize                      #finding the size of an element of g

4

In [35]:
h.itemsize                      #finding the size of element of h

4

In [36]:
h.dtype                        #finding datatype of h

dtype('int32')

In [37]:
g.size                         #finding the size of g
g

array([[1, 2, 4],
       [3, 5, 6]])

In [38]:
h.shape                       #finding the no.of rows & columns of h

(2, 3)

In [39]:
h.reshape(3,2)              #changing rows into columns and columns into rows

array([[7, 8],
       [9, 2],
       [6, 1]])

In [40]:
g.min()                 #finding min value of g

1

In [41]:
g.max()                 #finding max value of g

6

In [42]:
h.sum()                #finding the sum of h matrix

33

In [43]:
i=np.linspace(4,2,7)    #finding 7 values between 4 and 2
i

array([4.        , 3.66666667, 3.33333333, 3.        , 2.66666667,
       2.33333333, 2.        ])

In [44]:
g.sum(axis=1)             #getting sum of elements of rows in g

array([ 7, 14])

In [45]:
g.sum(axis=0)            #getting sum of elements of columns in g

array([ 4,  7, 10])

In [46]:
np.sqrt(g)              #finding square root of all elements in g

array([[1.        , 1.41421356, 2.        ],
       [1.73205081, 2.23606798, 2.44948974]])

In [47]:
np.std(h)              #finding standard deviation of h

2.9860788111948193

In [48]:
np.mean(h)            #finding total mean of h

5.5

In [49]:
g

array([[1, 2, 4],
       [3, 5, 6]])

In [50]:
h

array([[7, 8, 9],
       [2, 6, 1]])

In [55]:
g[0,2]        #finding 2nd element of 0th column

4

In [56]:
h[0:1,2]

array([9])

In [57]:
h[0:2,1]

array([8, 6])

In [59]:
g[1:2,1]

array([5])

In [60]:
g[g>2]      #finding the elements greater than 2

array([4, 3, 5, 6])

In [61]:
h.sort()  #sorting of elements in ascending order
h

array([[7, 8, 9],
       [1, 2, 6]])

In [62]:
h[h<3]      #finding the elements less than 3

array([1, 2])

In [66]:
h[h>=4]     #finding the elements which greater than or equal to 4

array([7, 8, 9, 6])

In [67]:
g+h        #addition of two matrices

array([[ 8, 10, 13],
       [ 4,  7, 12]])

In [68]:
g*h      #multiplication of two matrices

array([[ 7, 16, 36],
       [ 3, 10, 36]])

In [69]:
h.ravel()    #getting all elements in a same matrix

array([7, 8, 9, 1, 2, 6])

In [70]:
a

array('i')

In [71]:
b

array('i')

In [72]:
c.pop()             #pop operation

7